CREATE TABLE PorfolioItems (
    Id INT PRIMARY KEY,
    Year INT,
    AgileGroup NVARCHAR(200),
    Title NVARCHAR(200),
    Description NVARCHAR(MAX),
    Priority NVARCHAR(100),
    SapProject NVARCHAR(200),
    Front NVARCHAR(200),
    Country NVARCHAR(200),
    Contact NVARCHAR(200),
    Area NVARCHAR(200),
    Approval NVARCHAR(200),
    Progress NVARCHAR(100),
    CustomerPriority NVARCHAR(100),
    PoPriority NVARCHAR(100),
    Dependency NVARCHAR(100),
    Complexity INT,
    CountryFactor DECIMAL(18, 2),
    Weeks INT,
    People INT,
    LaborCostPerWeek DECIMAL(18, 2),
    OtherCosts DECIMAL(18, 2),
    Total DECIMAL(18, 2),
    RecurrentCosts DECIMAL(18, 2),
    Roi DECIMAL(18, 2),
    DevelopmentStart DATETIME,
    DevelopmentEnd DATETIME,
    PilotStart DATETIME,
    PilotEnd DATETIME,
    DeploymentStart DATETIME,
    DeploymentEnd DATETIME,
    Notes NVARCHAR(MAX),
    Roi2 DECIMAL(18, 2),
    Roi3 DECIMAL(18, 2)
);

CREATE TABLE PorfolioCosts (
    Id INT PRIMARY KEY,
    PorfolioItemId INT,
    Code NVARCHAR(200),
    Title NVARCHAR(200),
    Description NVARCHAR(MAX),
    SubTotal DECIMAL(18, 2),
    Taxes DECIMAL(18, 2),
    Total DECIMAL(18, 2),
    Date DATETIME
);
